#!/bin/bash
# Builds a Release Skift.app, ad-hoc signs it, and packages it into a
# mountable .dmg. Single source of truth for both local and CI releases —
# see docs/release-pipeline.md for the design.
#
# Usage: scripts/release.sh [marketing-version]
#   marketing-version defaults to "0.0.0-dev". It is stamped into
#   CFBundleShortVersionString/CFBundleVersion via xcodebuild build settings
#   at build time (project.yml's hardcoded "0.1.0" is a placeholder that
#   this script always overrides — we never rewrite project.yml).
#
# Prints the path to the produced .dmg as the last line of stdout.

set -euo pipefail

VERSION="${1:-0.0.0-dev}"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

BUILD_DIR="$ROOT_DIR/build"
DERIVED_DATA_PATH="$BUILD_DIR/DerivedData"
STAGING_DIR="$BUILD_DIR/staging"
DMG_PATH="$BUILD_DIR/Skift-$VERSION.dmg"

rm -rf "$STAGING_DIR"
rm -f "$DMG_PATH"
mkdir -p "$BUILD_DIR"

echo "==> Generating Xcode project (xcodegen)" >&2
xcodegen generate

echo "==> Building Skift.app (Release, version $VERSION)" >&2
xcodebuild -project Skift.xcodeproj -scheme Skift \
  -configuration Release \
  -destination 'platform=macOS' \
  -derivedDataPath "$DERIVED_DATA_PATH" \
  CODE_SIGNING_ALLOWED=NO \
  MARKETING_VERSION="$VERSION" \
  CURRENT_PROJECT_VERSION="$VERSION" \
  build

APP_PATH="$DERIVED_DATA_PATH/Build/Products/Release/Skift.app"
if [ ! -d "$APP_PATH" ]; then
  echo "error: Skift.app not found at $APP_PATH" >&2
  exit 1
fi

# Skift/Info.plist is generated by XcodeGen from project.yml's literal
# `properties:` block, so CFBundleShortVersionString/CFBundleVersion land
# in the source plist as plain strings ("0.1.0" / "1"), not $(MARKETING_VERSION)
# / $(CURRENT_PROJECT_VERSION) placeholders. Xcode's Info.plist build-setting
# substitution only fires for values that already use $(VAR) syntax in the
# source plist (that's why CFBundleExecutable etc. above pick up
# $(EXECUTABLE_NAME) correctly) — a literal value passes through unchanged.
# So MARKETING_VERSION/CURRENT_PROJECT_VERSION on the xcodebuild invocation
# above do NOT reach the built Info.plist by themselves. Patch the built
# bundle directly (before signing, so the signature covers the final
# contents) instead of hardcoding the version into project.yml.
echo "==> Stamping version $VERSION into built Info.plist" >&2
/usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION" "$APP_PATH/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $VERSION" "$APP_PATH/Contents/Info.plist"

# DECISION: ad-hoc sign (`-s -`) until a Developer ID exists. This keeps
# Gatekeeper's behavior consistent (the app always needs the same
# "right-click → Open" bypass on a fresh Mac) instead of sometimes being
# fully unsigned and sometimes signed, depending on who built it. Real
# Developer ID signing/notarization is stubbed in the release workflow,
# gated behind secrets that don't exist yet — see docs/release-pipeline.md.
echo "==> Ad-hoc signing Skift.app" >&2
codesign --force --deep -s - "$APP_PATH"

echo "==> Staging .dmg contents" >&2
mkdir -p "$STAGING_DIR"
cp -R "$APP_PATH" "$STAGING_DIR/Skift.app"
ln -s /Applications "$STAGING_DIR/Applications"

echo "==> Creating $DMG_PATH" >&2
hdiutil create -volname "Skift $VERSION" \
  -srcfolder "$STAGING_DIR" \
  -format UDZO \
  -ov \
  "$DMG_PATH"

rm -rf "$STAGING_DIR"

echo "$DMG_PATH"
